export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
// Basket actions
export const ADD_BASKET_SUCCESS = 'ADD_BASKET_SUCCESS';
export const ADD_BASKET_FAIL = 'ADD_BASKET_FAIL';

export const DELETE_BASKET_SUCCESS = 'DELETE_BASKET_SUCCESS';
export const DELETE_BASKET_FAIL = 'DELETE_BASKET_FAIL';

export const UPDATE_BASKET_SUCCESS = 'UPDATE_BASKET_SUCCESS';
export const UPDATE_BASKET_FAIL = 'DELETE_BASKET_FAIL';

export const GET_BASKET_SUCCESS = 'GET_BASKET_SUCCESS';
export const GET_BASKET_FAIL = 'GET_BASKET_FAIL';

export const GET_SINGLE_BASKET_SUCCESS = 'GET_SINGLE_BASKET_SUCCESS';

// Product actions

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';

export const GET_DEVIS_SUCCESS = 'GET_DEVIS_SUCCESS';
export const GET_DEVIS_FAIL = 'GET_DEVIS_FAIL';
export const GET_ALLDEVIS_SUCCESS = 'GET_ALLDEVIS_SUCCESS';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

// demande D'achat actions
export const ADD_DEMANDEACHAT_SUCCESS = 'ADD_DEMANDEACHAT_SUCCESS';
export const ADD_DEMANDEACHAT_FAIL = 'ADD_DEMANDEACHAT_FAIL';

export const DELETE_DEMANDEACHAT_SUCCESS = 'DELETE_DEMANDEACHAT_SUCCESS';
export const DELETE_DEMANDEACHAT_FAIL = 'DELETE_DEMANDEACHAT_FAIL';

export const UPDATE_DEMANDEACHAT_SUCCESS = 'UPDATE_DEMANDEACHAT_SUCCESS';
export const UPDATE_DEMANDEACHAT_FAIL = 'DELETE_DEMANDEACHAT_FAIL';

export const GET_DEMANDEACHAT_SUCCESS = 'GET_DEMANDEACHAT_SUCCESS';
export const GET_DEMANDEACHAT_FAIL = 'GET_DEMANDEACHAT_FAIL';

export const GET_SINGLE_DEMANDEACHAT_SUCCESS = 'GET_SINGLE_DEMANDEACHAT_SUCCESS';
